#!/bin/sh

set -e

# Upstalling Homebrew
if [[ $(command -v brew) == "" ]]; then
  echo "Installing Hombrew"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "Updating Homebrew"
  brew update
fi

brew bundle

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)"

# Self destruct
rm "${HOME}/.setup"
