#!/bin/zsh

function verbose() {
  [[ $DOTFILES_VERBOSE_OUTPUT == 1 ]] && echo $1
}

function chezmoi_apply_and_source() {
  verbose "🏡 Applying chezmoi changes"
  chezmoi apply
  verbose "💾 Sourcing ~/.zshrc"
  source "${HOME}/.zshrc"
}

function chezmoi_cd_and_code() {
  verbose "🏡 Coming home"
  chezmoi cd
  code .
}
