#!/bin/sh

set -e

echo "🏡 Making yourself at home..."

if [[ $(command -v brew) == "" ]]; then
  echo "🍺 Installing Hombrew"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "🍺 Updating Homebrew"
  brew update
fi

echo "📦 Installing Homebrew Packages"
brew bundle --file "${HOME}/.dotfiles/brew/Brewfile"

echo "Done!"
