#!/bin/zsh


echo "🏡 Goodbye!"

echo "🗑️ Deleting ~/.dotfiles/*"
rm -rf "${HOME}/.dotfiles"

echo "🗑️ Deleting ~/.dotfile"
rm "${HOME}/.dotfile"

echo "🧹 Removing 'source \"${HOME}/.dotfile\"' from ~/.zshrc"
sed -i '' '/source "${HOME}\/.dotfile"/d' "${HOME}/.zshrc"

echo "💾 Reloading ~/.zshrc"
source "${HOME}/.zshrc"

echo "✅ Done."

exec zsh
