#!/bin/zsh

echo "🏡 Making yourself at home..."

if [[ $(command -v brew) == "" ]]; then
  echo "🍺 Installing Hombrew"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" > /dev/null 2>&1
else
  echo "🍺 Updating Homebrew"
  brew update > /dev/null 2>&1
fi

echo "📦 Installing Homebrew Packages"
brew bundle --file "${HOME}/.dotfiles/brew/Brewfile" > /dev/null 2>&1

echo "💾 Updating ~/.zshrc file"
local injection='source "${HOME}/.dotfile"'
if ! grep -Fxq "${injection}" "${HOME}/.zshrc"; then
  echo "${injection}" >> "${HOME}/.zshrc"
fi

echo "💾 Sourcing ~/.zshrc file"
source "${HOME}/.zshrc"

echo "✅ Done."
