#!/bin/zsh

# set -e

echo "🏡 Making yourself at home..."

if [[ $(command -v brew) == "" ]]; then
  echo "🍺 Installing Hombrew"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "🍺 Updating Homebrew"
  brew update
fi

echo "📦 Installing Homebrew Packages"
brew bundle --file "${HOME}/.dotfiles/brew/Brewfile"

# have "${HOME}/.dotfile" "#!/bin/zsh\n"

echo "Creating custom ~/.dotfile"
local $zshrc_injection='source "${HOME}/.dotfile"'
echo "----"
echo $injection
echo "----"

if [[ ! -f "${HOME}/.dotfile" ]]; then
  # touch "${HOME}/.dotfile"
  local $injection="\. \"\$\{HOME\}\/.dotfile\""
  echo "----"
  echo $injection
  echo "----"
  # echo "#!/bin/zsh\n\nverbose '🏡 Home sweet home'" > "${HOME}/.dotfile"
else
  verbose "~/.dotfile already exists!"
fi

echo "Done ~ 🏡 Welcome home!"
