#!/bin/zsh

function verbose() {
  if [[ $DOTFILES_VERBOSE_OUTPUT != 0 ]]; then
    echo "${1}"
  fi
}

function very_verbose() {
  if [[ $DOTFILES_VERY_VERBOSE_OUTPUT != 0 ]]; then
    echo "${1}"
  fi
}

# Checks whether a function exists
function function_exists() {
  if compgen -A function | grep -q "^${1}$"; then
    return 0
  else
    return 1
  fi
}

# Lists dotfile_* functions as commands
# IDEA: Should the prefix be invokable_ or callable_ instead of dotfile_?
function available_dotfile_commands() {
  local prefix="${1:-dotfile_}"
  compgen -A function | grep "^${prefix}" | sed "s/^${prefix}/- /"
}

function available_dotfile_executables() {
  find "${HOME}/.dotfiles" -maxdepth 1 -type f -perm -u+x -exec basename {} \; | awk '{print "- " $0}'
}

function source_dotfile_modules() {
  for module in "${HOME}/.dotfiles/modules"/*; do
    if [[ -d "${module}" ]]; then
      for file in "${module}"/*; do
        source "${file}"
      done
    fi
  done
}

function source_dotfile() {
  verbose "💾 Sourcing ~/.dotfile"
  source "${HOME}/.dotfile"
}


# Invokes any existing dotfile_ prefixed function
# Usage:
# - dotfile save
# - dotfile run setup
# IDEA: Should the prefix be executable_ instead of dotfile_?
function dotfile() {
  local function_name="dotfile_${1}"
  local function_arguments="${*:2}"

  if function_exists "${function_name}"; then
    verbose "Calling function: ${function_name} with argument: ${2}"
    "${function_name}" "${function_arguments}"
  else
    verbose "Error: dotfile command '${1}' does not exist"
    echo "--------------------------------------------"
    echo "Available dotfile commands:"
    available_dotfile_commands
  fi
}

# Runs executable script within ~/.dotfiles
# Usage: dotfile run setup
function dotfile_run() {
  verbose "Invoking dotfile_run $@"
  local script="${HOME}/.dotfiles/${1}"

  if [[ ! -f $script ]]; then
    echo "Error: '${script}' is not an executable file"
    echo "--------------------------------------------"
    echo "Available executable scripts in ~/.dotfiles:"
    available_dotfile_executables
  else
    verbose "Running: ${script}"
    . "${script}"
  fi
}

function dotfile_save() {
  verbose "🏡 Applying chezmoi changes"
  chezmoi apply
  source_dotfile
}

function dotfile_update() {
  verbose "🏡 Updating remote chezmoi changes"
  chezmoi update
  source_dotfile
  very_verbose "Done."
}

function dotfile_edit() {
  verbose "🏡 Coming home"
  chezmoi cd
  code .
  very_verbose "🏡 Welcome back!"
}

function current_file() {
  echo "${(%):-%x}"
}
