#!/bin/sh

echo "🏡 Making yourself at home..."

if [[ $(command -v brew) == "" ]]; then
  echo "🍺 Installing Hombrew"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" > /dev/null 2>&1
else
  echo "🍺 Updating Homebrew"
  brew update > /dev/null 2>&1
fi

echo "📦 Installing zsh"
brew install zsh > /dev/null 2>&1

echo "💾 Setting zsh as the default shell"
chsh -s $(which zsh) > /dev/null 2>&1

echo "📦 Installing chezmoi"
brew install chezmoi > /dev/null 2>&1

echo "🏡 Initializing chezmoi"
chezmoi init benvilliere > /dev/null 2>&1

echo "🏡 Applying chezmoi"
chezmoi apply

echo "📦 Installing Homebrew Packages"
brew bundle --file "${HOME}/.dotfiles/brew/Brewfile" > /dev/null 2>&1

echo "💾 Updating ~/.zshrc file"
zshrc_directive='source "${HOME}/.dotfile"'
if ! grep -Fxq "${zshrc_directive}" "${HOME}/.zshrc"; then
  echo "${zshrc_directive}" >> "${HOME}/.zshrc"
fi

echo "💾 Sourcing ~/.zshrc file"
zsh "${HOME}/.zshrc"

echo "✅ Done."
exec zsh
