#!/bin/sh

echo "🏡 Goodbye!"

echo "🗑️ Purging chezmoi"
chezmoi purge --force
rm -rf "${HOME}/.local/share/chezmoi"

echo "🗑️ Uninstalling chezmoi"
brew uninstall chezmoi

echo "🗑️ Deleting ~/.dotfiles/*"
rm -rf "${HOME}/.dotfiles"

echo "🗑️ Deleting ~/.dotfile"
rm "${HOME}/.dotfile"

echo "🧹 Cleaning up ~/.zshrc file"
sed -i '' '/source "${HOME}\/.dotfile"/d' "${HOME}/.zshrc"

echo "💾 Reloading ~/.zshrc"
. "${HOME}/.zshrc"

exec zsh

echo "✅ Done."
